repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: pretty-format-json
    args: ['--autofix', '--no-sort-keys', '--indent=2']
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
- repo: https://github.com/hadialqattan/pycln
  rev: v0.0.1-beta.3
  hooks:
  - id: pycln
    args: [--config=pyproject.toml]
- repo: https://github.com/pycqa/isort
  rev: 5.5.4
  hooks:
  - id: isort
    files: "\\.(py)$"
    args: [--settings-path=pyproject.toml]
