version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: kelvin.vu@ucars.sg
  #     PGADMIN_DEFAULT_PASSWORD: kelvin
  #   ports:
  #     - "5050:80"
volumes:
  db:
    driver: local
